version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: miner-monitor-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - MINER_MONITOR_DEBUG=false
      - MINER_MONITOR_HOST=0.0.0.0
      - MINER_MONITOR_PORT=8000
      - MINER_MONITOR_LOG_LEVEL=WARNING
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - miner-monitor-network

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: miner-monitor-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - miner-monitor-network

networks:
  miner-monitor-network:
    driver: bridge
    name: miner-monitor-network

volumes:
  data:
    driver: local
  logs:
    driver: local